[package]
name = "taitoh"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
env_logger = "0.11.6"
log = "0.4.25"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
